# Build stage
FROM node:18.20.4-alpine3.20 as build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Production stage
FROM nginx:alpine

# Copy built files from the build stage
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80 for serving the site
EXPOSE 80

# Default command to run the Nginx server
CMD ["nginx", "-g", "daemon off;"]
